#!/bin/sh
# JWCode Docker entrypoint
# Handles: Docker socket permissions, config generation from env vars, privilege drop
set -e

# --- Docker socket permission fix ---
# If the Docker socket is mounted, detect its GID and add jwcode user to that group
if [ -S /var/run/docker.sock ]; then
    DOCKER_GID=$(stat -c '%g' /var/run/docker.sock 2>/dev/null || stat -f '%g' /var/run/docker.sock 2>/dev/null)
    if [ -n "$DOCKER_GID" ] && [ "$DOCKER_GID" -gt 0 ] 2>/dev/null; then
        # Create docker group with the same GID as the host
        addgroup -S docker -g "$DOCKER_GID" 2>/dev/null || true
        adduser jwcode docker 2>/dev/null || true
    fi
fi

# --- Config generation ---
CONFIG_DIR="/home/jwcode/.jwcode"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
DEFAULT_PROVIDER="${JWCODE_PROVIDER:-deepseek}"

# Provider defaults mapping
# shellcheck disable=SC2034
PROVIDER_DEFAULTS="
deepseek|https://api.deepseek.com|openai-completions|deepseek-chat|8192
claude|https://api.anthropic.com|anthropic-messages|claude-sonnet-4-20250514|8192
openai|https://api.openai.com/v1|openai-completions|gpt-4o|8192
"

_provider_default() {
    # $1 = provider name, $2 = field index (1=base_url, 2=api_type, 3=model, 4=max_tokens)
    echo "$PROVIDER_DEFAULTS" | while IFS='|' read -r name base api_type model maxtok; do
        [ "$name" = "$1" ] && echo "$base" && break
    done
    # Return the specific field
    echo "$PROVIDER_DEFAULTS" | while IFS='|' read -r name base api_type model maxtok; do
        [ "$name" = "$1" ] || continue
        case "$2" in
            1) echo "$base" ;;
            2) echo "$api_type" ;;
            3) echo "$model" ;;
            4) echo "$maxtok" ;;
        esac
        break
    done
}

generate_config() {
    mkdir -p "$CONFIG_DIR"

    # Start YAML
    {
        echo "# JWCode configuration — auto-generated by Docker entrypoint"
        echo "# To customize, mount a config.yaml to ${CONFIG_FILE}"
        echo ""

        # Collect providers that have API keys set
        PROVIDERS=""
        for var in $(env | grep '^JWCODE_API_KEY_' | sed 's/=.*//'); do
            key_value=$(eval echo "\$$var")
            [ -z "$key_value" ] && continue
            provider=$(echo "$var" | sed 's/^JWCODE_API_KEY_//' | tr '[:upper:]' '[:lower:]')
            PROVIDERS="$PROVIDERS $provider"
        done

        if [ -z "$PROVIDERS" ]; then
            # No env var keys found — write a minimal config with empty providers
            # User can mount their own config.yaml
            cat << 'YAML_EMPTY'
# No API keys found in environment variables.
# Set JWCODE_API_KEY_DEEPSEEK, JWCODE_API_KEY_CLAUDE, etc. in your .env file
# or mount a pre-configured config.yaml to this path.

default-provider: deepseek

providers: {}
YAML_EMPTY
            return
        fi

        # Write default provider
        echo "default-provider: ${DEFAULT_PROVIDER}"
        echo ""
        echo "providers:"

        # Write each provider
        for provider in $PROVIDERS; do
            # Uppercase version for env var lookup
            prov_upper=$(echo "$provider" | tr '[:lower:]' '[:upper:]')

            # Get API key
            api_key_var="JWCODE_API_KEY_${prov_upper}"
            api_key=$(eval echo "\$$api_key_var")

            # Get optional overrides from env vars
            base_url_var="JWCODE_BASE_URL_${prov_upper}"
            base_url_override=$(eval echo "\$$base_url_var" 2>/dev/null || echo "")

            model_var="JWCODE_MODEL_${prov_upper}"
            model_override=$(eval echo "\$$model_var" 2>/dev/null || echo "")

            # Look up defaults
            base_url=$(echo "$PROVIDER_DEFAULTS" | while IFS='|' read -r name base api_type model maxtok; do
                [ "$name" = "$provider" ] && echo "$base" && break
            done)
            api_type=$(echo "$PROVIDER_DEFAULTS" | while IFS='|' read -r name base api_type model maxtok; do
                [ "$name" = "$provider" ] && echo "$api_type" && break
            done)
            default_model=$(echo "$PROVIDER_DEFAULTS" | while IFS='|' read -r name base api_type model maxtok; do
                [ "$name" = "$provider" ] && echo "$model" && break
            done)
            max_tokens=$(echo "$PROVIDER_DEFAULTS" | while IFS='|' read -r name base api_type model maxtok; do
                [ "$name" = "$provider" ] && echo "$maxtok" && break
            done)

            # Apply overrides
            [ -n "$base_url_override" ] && base_url="$base_url_override"
            [ -n "$model_override" ] && default_model="$model_override"
            [ -z "$base_url" ] && base_url="https://api.${provider}.com"
            [ -z "$api_type" ] && api_type="openai-completions"
            [ -z "$default_model" ] && default_model="${provider}-chat"
            [ -z "$max_tokens" ] && max_tokens="8192"

            cat << YAML_PROVIDER
  ${provider}:
    base-url: ${base_url}
    api-type: ${api_type}
    api-keys: [ ${api_key} ]
    models:
      - id: ${default_model}
        max-tokens: ${max_tokens}
YAML_PROVIDER
        done
    } > "$CONFIG_FILE"

    echo "[jwcode] Config generated at ${CONFIG_FILE}" >&2
}

if [ ! -f "$CONFIG_FILE" ]; then
    generate_config
else
    echo "[jwcode] Using existing config at ${CONFIG_FILE}" >&2
fi

# Fix ownership of config directory
chown -R jwcode:jwcode "$CONFIG_DIR" 2>/dev/null || true

# --- Drop privileges and execute CMD ---
exec su-exec jwcode:jwcode "$@"
