package com.jwcode.core.parser.treesitter;

/**
 * An object that defines how to parse a particular language.
 *
 * <p>In the real tree-sitter core, this corresponds to {@code TSLanguage} (api.h L44),
 * which is an opaque struct generated by the Tree-sitter CLI. In our pure-Java
 * implementation, it acts as a parser factory + grammar metadata.</p>
 */
public abstract class Language {
    private final String name;

    protected Language(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    /**
     * Parse the given source code and produce a syntax tree.
     *
     * @param source the source code text
     * @param oldTree previous syntax tree for incremental parsing (may be null)
     * @return the parsed syntax tree, or null if parsing failed
     */
    public abstract Tree parse(String source, Tree oldTree);
}
